### ISSUE TITLE
Online example?

### ISSUE THREAD

**Issue by ghost** [suvajitgupta/Tasks#15]
Can't you make an online example so we don't have to install Persevere?

Just like http://create.tpsitulsa.com/static/contacts/

Would be really helpful.

**Comment by joshholt** [comment]
We have an online example:

http://tasks-demo.appspot.com/

Hope this helps...

**Comment by suvajitgupta** [comment]
If you want to run locally you can set 'serverType' to 0x0000 (NO_SERVER) in 'core.js' which will run Tasks in FIXTURES mode which won't require Persevere.

Is that what you were asking?

**Comment by ghost** [comment]
Not really but that was good information!

You already have an online example: http://tasks.sproutcore.com/tasks

Thanks.
