### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by sergiobayona** [suvajitgupta/Tasks#16]
I've followed the README to the letter and when I go to http://localhost:4400/tasks I see this error on my console:

  SC.MasterDetailView is undefined
  [Break On This Error] masterDetailView: SC.MasterDetailView.design({  ....

Any ideas?
SB

**Comment by suvajitgupta** [comment]
are you using suvajitgupta/sproutcore?  that is an almost SC 1.5 version from late last year and has MasterDetailView in it.

**Comment by suvajitgupta** [comment]
hopefully my email clarified what you need to do?
