### ISSUE TITLE
Tasks app server crashes on first request

### ISSUE THREAD

**Issue by pangloss** [suvajitgupta/Tasks#2]
When I run sc-server and make a request in the browser I get the following error message:

```
RuntimeError at /tasks
html_builder could not find a layout file for sproutcore:lib/index.rhtml
Ruby    /Users/dw/.gem/ruby/1.8/gems/sproutit-sproutcore-1.0.20090721145285/lib/sproutcore/builders/html.rb: in render, line 106
Web     GET localhost/tasks
```

I'm using the most current sproutit-sproutcore gem from github: 

```
sproutit-sproutcore-1.0.20090721145285
```

I tried both the master and the demo branch but had the same problem.

**Comment by suvajitgupta** [comment]
You have an empty sproutcore folder in Tasks. He needs to run git submodule update --init and restart.

**Comment by suvajitgupta** [comment]
fixed all of these
