### ISSUE TITLE
tasks deployed on Google App Engine, why not on Typhoon App Engine (i.e. your own GAE backend)

### ISSUE THREAD

**Issue by angusyoung** [suvajitgupta/Tasks#3]
Hi,

TyphoonAE is a great project that permit you to host Google App Engine apps on your own back-end(E2C VMs, rack, slice, etc.).

It would be great if tasks installation process and sources for GAE were published. Thus, people who wants to deploy it on their own backend with scalability in mind could use TyphoonAE to do so.

Take a look at TyphoonAE:
http://code.google.com/p/typhoonae/

Keep the good work!

**Comment by joshholt** [comment]
The deployment on GAE is on github here http://github.com/joshholt/SproutCoreTasks-AppEngineBackend
