### ISSUE TITLE
user-add.sh doesn't hash passwords

### ISSUE THREAD

**Issue by ynniv** [suvajitgupta/Tasks#4]
The README is currently broken because user-add.sh puts passwords into the database as plaintext, but tasks submits the password in hashed form.  Workaround by opening a JavaScript console for tasks, executing "Tasks.Sha1.sha1Hash(yourpassword)", and setting the user password manually via http://localhost:8088/tasks-server/explorer.html.

**Comment by seidemiller** [comment]
This should be fixed now.  Thanks!
