### ISSUE TITLE
Instructions for installation are incorrect, sha1sum issue

### ISSUE THREAD

**Issue by aiwilliams** [suvajitgupta/Tasks#5]
Hello. That 'git reset --hard' is incorrect when executed exactly as described. The person must first 'cd sproutcore' (move into the newly cloned sproutcore framework directory). That commit object is in that repository, not the tasks repository.

sha1sum doesn't exist on Mac OSX v.10.6.2. I had to modify the user-add.sh script to use 'openssl sha1' in place of 'sha1sum' (keeping all else the same).

Then it worked! Great app, and a wonderful example of using the framework. Thank you!

**Comment by joshholt** [comment]
Thanks for pointing this out... has helped other users
