### ISSUE TITLE
Window Does Not Correctly Resize

### ISSUE THREAD

**Issue by timtadh** [suvajitgupta/Tasks#7]
On my laptop screen 1280x800px the bottom of the main is chopped off. For instance I cannot see the [+][-] buttons for adding tasks.

**Comment by suvajitgupta** [comment]
Thanks for reporting this.  Do you mind sending me a screenshot to suvajit_gupta@eloqua.com?

**Comment by timtadh** [comment]
When I updated to the latest the issue seems to have been resolved.
