### ISSUE TITLE
SCUI is not defined

### ISSUE THREAD

**Issue by wuzongbin2008** [suvajitgupta/Tasks#9]
l put scui into the frameworks yet,but, SCUI is not defined.why

**Comment by suvajitgupta** [comment]
Did you follow the README steps precisely?  It should work...

**Comment by wuzongbin2008** [comment]
README of the Tasks folder ?

**Comment by suvajitgupta** [comment]
yes - top level

**Comment by wuzongbin2008** [comment]
can you  give me a full tasks source core? l can't deploy; thank you very much;l m a beginner

**Comment by suvajitgupta** [comment]
the full source code is pushed up - get Tasks and follow the README steps

**Comment by wuzongbin2008** [comment]
but,it has no SCUI that the full source code is pushed up.l follow the README steps to do.but,l faild

**Comment by wuzongbin2008** [comment]
l m chinese,l isn't good at english

**Comment by suvajitgupta** [comment]
the README tells you to clone another repo SCUI

**Comment by wuzongbin2008** [comment]
l do it yet,but faild;l do it 2 days. l try out it follow the README again.thank you very much! can you give me your msn? l need your help

**Comment by wuzongbin2008** [comment]
my wuzongbin2008@hotmail.com
my name:jet
my email: wuzongbin2008@gmail.com
thank you

**Comment by suvajitgupta** [comment]
New README should fix all your issues
